### ISSUE TITLE
HStack alignment

### ISSUE THREAD

**Issue by andredewaard** [swiftui-library/hstack-snap-to-scroll#5]
Is there a way to align all the items to the top.
Normally HStack alignment is used to align the items inside to the desired position.
For HStackSnap it is used for where it should snap.

I'm trying to recreate what you have in example 2 but with 3 items above each other. My search result doesn't always give me a multiple of 3 since sometimes there are only 8 results. when this happens the last 2 are aligned in the middle

**Comment by andredewaard** [comment]
Fixed this with `GeometryReader` and adding a frame to the VStack that has the height of the geometryReader
```
GeometryReader { reader in
    HStackSnap(alignment: .leading(16)) {
        ForEach(0..<chunkedUsers.count) { index in
            VStack(alignment: .leading) {
                ForEach(chunkedUsers[index]) { user in
                    UserRow(user: user)
                        .frame(width: 300, alignment: .leading)
                        .background(NavigationLink(destination: UserView(user: user), tag: user.id, selection: $activeUser) {
                            EmptyView()
                        })
                        .snapAlignmentHelper(id: user.id)
                        .onTapGesture {
                            activeUser = user.id
                        }
                }
            }
            .frame(height: reader.size.height, alignment: .top)
        }
    }
}
```

**Comment by trentguillory** [comment]
Thanks for sharing your solution!
